{
  "contest": 188,
  "handle": "helios",
  "risk": "2",
  "title": "\"Error when calling executeCalls function with already executed calls\"",
  "issueId": 121,
  "issueUrl": "https://github.com/code-423n4/2022-12-pooltogether-findings/issues/121"
}